#!/bin/bash
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <test_set_file>" >&2
else
    #iterating 
    for stem in $(cat "$1"); do
        descfile="${stem}.desc"
        #if the description file is there
        if [ -f "$descfile" ]; then
            #print
            cat "$descfile"
        else
            #if the description file is not there
            echo "${stem} No test description"
        fi
    done
fi



